// Code generated by codegen; DO NOT EDIT.

package frauddetector

import (
	"github.com/cloudquery/cloudquery/plugins/source/aws/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func ModelVersion() *schema.Table {
	return &schema.Table{
		Name:      "aws_frauddetector_model_version",
		Resolver:  fetchFrauddetectorModelVersion,
		Multiplex: client.ServiceAccountRegionMultiplexer("frauddetector"),
		Columns: []schema.Column{
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Arn"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "model_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ModelId"),
			},
			{
				Name:     "model_type",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ModelType"),
			},
			{
				Name:     "model_version_number",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ModelVersionNumber"),
			},
		},
	}
}
